stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: nexus:443/node:18-alpine
  script:
    - npm install
    - npm run build
    - npm run test --if-present

deploy:
  stage: deploy
  image:
    name: nexus:443/ubuntu:20.04
  script:
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy-updates main restricted universe' > /etc/apt/sources.list -
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy main restricted universe' >> /etc/apt/sources.list
    - apt-get update && apt-get install -y python3 python3-pip openssh-client sudo
    - useradd -d /home/ansible -m -s /bin/bash ansible
    - tar czf /home/ansible/app.tar.gz . && cp front.service 00-front.conf frontapp /home/ansible && chown ansible:ansible /home/ansible/*
    - sudo -u ansible -s /bin/bash -c '/usr/bin/pip install --index-url http://10.27.95.5:8081/repository/pypi-all/simple --trusted-host 10.27.95.5 ansible'
    - sudo -u ansible -s /bin/bash -c "mkdir /home/ansible/inventory; echo ics-sec ansible_host=10.27.95.1 ansible_ssh_user=ansible ansible_become_pass=`echo $ANSIBLE_PASSWORD | base64 -d` >/home/ansible/inventory/hosts"
    - mkdir /home/ansible/.ssh; chown ansible:ansible /home/ansible/.ssh; chmod 700 /home/ansible/.ssh
    - echo $ANSIBLE_PRIVATE_KEY | base64 -d > /home/ansible/.ssh/id_rsa; chown ansible:ansible /home/ansible/.ssh/id_rsa; chmod 0600 /home/ansible/.ssh/id_rsa
    - cp playbook.yml /home/ansible/playbook.yml; chown ansible:ansible /home/ansible/playbook.yml
    - sudo -u ansible -s /bin/bash -c '/usr/bin/ssh-keygen -f /home/ansible/.ssh/id_rsa -y > /home/ansible/.ssh/id_rsa.pub'
    - sudo -u ansible -s /bin/bash -c 'export ANSIBLE_HOST_KEY_CHECKING=False; /home/ansible/.local/bin/ansible-playbook /home/ansible/playbook.yml -i /home/ansible/inventory/hosts'
