stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: nexus:443/node:18-alpine
  script:
    - npm install
    - npm run build
    - npm run test --if-present

deploy:
  stage: deploy
  only:
    - main
  image:
    name: nexus:443/netpardaz/ubuntu-ansible:20.04
  script:
    - mkdir /home/ansible/inventory
    - echo ics-sec ansible_host=10.27.95.1 ansible_ssh_user=ansible ansible_become_pass=`echo $ANSIBLE_PASSWORD | base64 -d` >/home/ansible/inventory/hosts
    - echo $ANSIBLE_PRIVATE_KEY | base64 -d > /home/ansible/.ssh/id_rsa; chmod 0600 /home/ansible/.ssh/id_rsa
    - /usr/bin/ssh-keygen -f /home/ansible/.ssh/id_rsa -y > /home/ansible/.ssh/id_rsa.pub
    - export ANSIBLE_HOST_KEY_CHECKING=False; /home/ansible/.local/bin/ansible-playbook /home/ansible/playbook.yml -i /home/ansible/inventory/hosts
