stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: nexus:443/node:18-alpine
  script:
    - npm install
    - npm run build
    - npm run test --if-present

deploy:
  stage: deploy
  image:
    name: nexus:443/ubuntu:20.04
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_PRIVATE_KEY")
  script:
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy-updates main restricted universe' > /etc/apt/sources.list -
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy main restricted universe' >> /etc/apt/sources.list
    - apt-get update && apt-get install -y python3 python3-pip 
    - pip install --index-url http://10.27.95.5:8081/repository/pypi-all/simple --trusted-host 10.27.95.5 ansible
    - mkdir inventory
    - 'echo "10.27.95.1 ansible_host=ics-sec ansible_ssh_user=ansible" >inventory/hosts'
    - ls -la
    - whoami
    - ansible-playbook --version
    - ansible-playbook ./ansible/playbook.yml -i ./ansible/hosts
