stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: nexus:443/node:18-alpine
  script:
    - npm install
    - npm run build
    - npm run test --if-present

deploy:
  stage: deploy
  image:
    name: nexus:443/ubuntu:20.04
  script:
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy-updates main restricted universe' > /etc/apt/sources.list -
    - echo 'deb http://10.27.95.5:8081/repository/apt-proxy/ubuntu jammy main restricted universe' >> /etc/apt/sources.list
    - apt-get update && apt-get install -y python3 python3-pip openssh-client sudo
    - useradd -d /home/ansible -m -s /bin/bash ansible
    - sudo -u ansible -s /bin/bash -c '/usr/bin/pip install --index-url http://10.27.95.5:8081/repository/pypi-all/simple --trusted-host 10.27.95.5 ansible'
    - sudo -u ansible -s /bin/bash -c 'mkdir /home/ansible/inventory; ANSIBLE_BECOME_PASS=$(echo $ANSIBLE_PASSWORD | base64 -d); echo "10.27.95.1 ansible_host=ics-sec ansible_ssh_user=ansible ansible_become_passw=${ANSIBLE_BECOME_PASS}" >/home/ansible/inventory/hosts'
    - mkdir /home/ansible/.ssh; chown ansible:ansible /home/ansible/.ssh; chmod 700 /home/ansible/.ssh
    - echo $ANSIBLE_PRIVATE_KEY | base64 -d > /home/ansible/.ssh/id_rsa; chown ansible:ansible /home/ansible/.ssh/id_rsa; chmod 0600 /home/ansible/.ssh/id_rsa
    - cat -Av /home/ansible/inventory/hosts
    - cat -Av /home/ansible/.ssh/id_rsa
    - sudo -u ansible -s /bin/bash -c '/usr/bin/ssh-keygen -f /home/ansible/.ssh/id_rsa -y > /home/ansible/.ssh/id_rsa.pub'
    - sudo -u ansible -s /bin/bash -c '/home/ansible/.local/bin/ansible-playbook /home/ansible/playbook.yml -i ./ansible/inventory/hosts'
