- hosts: ics-sec
  become: yes
  become_user: root
  gather_facts: yes

  # Variables
  vars:
    ansible_python_interpreter: /usr/bin/python3

  # List of tasks
  tasks:
  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install sanpd
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items:
      - snap
      - python3
      - python3-lxc
      - lxc
      - lxc-dev
      - lxc-templates
      - lxc-utils
      - liblxc-common
      - liblxc-dev

  - name: Install lxd using snap
    community.general.snap:
      name:
        - lxd
  
  - name: Create front container
    ansible.builtin.command:
      cmd: /snap/bin/lxc launch ubuntu:20.04 front
      creates: /var/snap/lxd/common/lxd/containers/zeek
 
  - name: Install nodejs in container
    ansible.builtin.command:
      cmd: /snap/bin/lxc exec front -- /bin/bash -c "apt-get update && apt-get dist-upgrade -y && curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && apt-get update && apt-get install nodejs -y"
