- hosts: ics-sec
  become: yes
  become_user: root
  gather_facts: yes

  # Variables
  vars:
    ansible_python_interpreter: /usr/bin/python3

  # List of tasks
  tasks:
  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes

  - name: Install sanpd
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items:
      - snap
      - python3
      - python3-lxc
      - lxc
      - lxc-dev
      - lxc-templates
      - lxc-utils
      - liblxc-common
      - liblxc-dev

  - name: Install lxd using snap
    community.general.snap:
      name:
        - lxd
  
  - name: Create front container
    community.general.lxd_container:
      name: front
      ignore_volatile_options: true
      state: started
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: lxd # if you get a 404, try setting protocol: simplestreams
        alias: ubuntu/jammy/amd64
      profiles: ["default"]
      wait_for_ipv4_addresses: true
      timeout: 600
 
  - name: Install python in container
    delegate_to: mycontainer
    ansible.builtin.raw: | 
      apt-get update && apt-get dist-upgrade 
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      apt-get update
      apt-get install nodejs
