- hosts: ics-sec
  become: yes
  become_user: root
  gather_facts: yes

  # Variables
  vars:
    ansible_python_interpreter: /usr/bin/python3
    containers:
      front:
        ip_address: '10.27.95.201'

  # List of tasks
  tasks:
    - name: Copy application
      ansible.builtin.copy:
        src: '/home/ansible/{{ item }}'
        dest: '/tmp/{{ item }}'
        owner: root
        group: root
        mode: '0644'
      with_items:
        - app.tar.gz
        - front.service
        - '00-front.conf'
        - frontapp

    - name: Ensure front container IP address is present in dnsmasq configuration
      ansible.builtin.lineinfile:
        path: /etc/lxc/dnsmasq.conf
        regexp: '^dhcp-host=front'
        line: 'dhcp-host=front,{{ containers.front.ip_address }}'
      notify:
        - Restart lxd network

    - name: Flush Handlers
      meta: flush_handlers

    - name: Create front container
      ansible.builtin.command:
        cmd: /snap/bin/lxc launch ubuntu:20.04 front
        creates: /var/snap/lxd/common/lxd/containers/front

    - name: Make sure container is started
      community.general.lxd_container:
        name: front
        state: started

    - name: Install nodejs and deploy application into the container
      ansible.builtin.shell: |
        sleep 5
        /snap/bin/lxc config device add front eth0 nic name=eth0 nictype=bridged parent=vsys0
        /snap/bin/lxc exec front -- /bin/bash -c "egrep '^192.168.1.50\snexus$' /etc/hosts || echo 192.168.1.50 nexus >>/etc/hosts"
        /snap/bin/lxc exec front -- /bin/bash -c "echo deb http://nexus:8081/repository/apt-proxy/ubuntu jammy-updates main restricted universe > /etc/apt/sources.list && echo deb http://nexus:8081/repository/apt-proxy/ubuntu jammy main restricted universe >> /etc/apt/sources.list"
        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade  -y -q
        /snap/bin/lxc exec front -- /bin/bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' -y -q"
        /snap/bin/lxc exec front -- /bin/bash -c "curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install nodejs -y -q"
        /snap/bin/lxc file push /tmp/app.tar.gz front/tmp/app.tar.gz
        /snap/bin/lxc file push /tmp/front.service front/usr/lib/systemd/system/front.service
        /snap/bin/lxc file push /tmp/00-front.conf front/etc/rsyslog.d/00-front.conf
        /snap/bin/lxc file push /tmp/frontapp front/etc/logrotate.d/frontapp
        /snap/bin/lxc exec front -- /bin/bash -c "grep front /etc/passwd >/dev/null || useradd -d /home/front -m -s /usr/sbin/nologin front && tar -C /home/front -xzf /tmp/app.tar.gz && systemctl enable front.service && mkdir /var/log/frontapp && chown syslog:adm /var/log/frontapp && systemctl restart rsyslog"
        /snap/bin/lxc file push /tmp/.env.production front/home/front/.env.production
        /snap/bin/lxc exec front -- /bin/bash -c "cd /home/front/ && npm install && npm run build"
        /snap/bin/lxc exec front -- /bin/bash -c "chown -R front:front /home/front/"
        /snap/bin/lxc exec front -- /bin/bash -c "systemctl daemon-reload && systemctl restart front.service"

    - name: template front.conf to nginx
      ansible.builtin.template:
        src: front.conf.j2
        dest: /opt/nginx/sites-available/front.conf
        mode: '0644'
      notify:
      - Restart nginx service

    - name: Create a symbolic link to front.conf from enabled sites of nginx
      ansible.builtin.file:
        src: /opt/nginx/sites-available/front.conf
        dest: /opt/nginx/sites-enabled/front.conf
        state: link
      notify:
      - Restart nginx service

  handlers:
    - name: Restart lxd network
      ansible.builtin.systemd:
        state: restarted
        name: lxc-net

    - name: Restart nginx service
      ansible.builtin.systemd:
        state: restarted
        name: nginx
