export const PALLET = {
  LIGHT: {
    BG_COLOR: {
      PRIMARY: 'bg-sky-100',
      SUCCESS: 'bg-green-100',
      INFO: 'bg-orange-100',
      ERROR: 'bg-red-100',
      WARNING: 'bg-orange-100',
      GRAY: 'bg-neutral-100',
      DEFAULT: 'bg-white',
    },
    TEXT_COLOR: {
      PRIMARY: 'text-sky-600',
      SUCCESS: 'text-green-600',
      INFO: 'text-blue-600',
      ERROR: 'text-red-600',
      WARNING: 'text-orange-600',
      GRAY: 'text-neutral-600',
      DEFAULT: 'text-black',
    },
    BORDER_COLOR: {
      PRIMARY: 'border-sky-100',
      SUCCESS: 'border-green-600',
      INFO: 'border-blue-600',
      ERROR: 'border-red-600',
      WARNING: 'border-orange-600',
      GRAY: 'border-neutral-600',
      DEFAULT: 'border-white',
    },
  },
  DARK: {
    BG_COLOR: {
      PRIMARY: 'dark:bg-sky-100',
      SUCCESS: 'dark:bg-green-100',
      INFO: 'dark:bg-blue-100',
      ERROR: 'dark:bg-red-100',
      WARNING: 'dark:bg-orange-100',
      GRAY: 'dark:bg-neutral-100',
      DEFAULT: 'dark:bg-white',
    },
    TEXT_COLOR: {
      PRIMARY: 'dark:text-sky-600',
      SUCCESS: 'dark:text-green-600',
      INFO: 'dark:text-blue-600',
      ERROR: 'dark:text-red-600',
      WARNING: 'dark:text-orange-600',
      GRAY: 'dark:text-neutral-600',
      DEFAULT: 'dark:text-black',
    },
    BORDER_COLOR: {
      PRIMARY: 'dark:border-sky-600',
      SUCCESS: 'dark:border-green-600',
      INFO: 'dark:border-blue-600',
      ERROR: 'dark:border-red-600',
      WARNING: 'dark:border-orange-600',
      GRAY: 'dark:border-neutral-600',
      DEFAULT: 'dark:border-white',
    },
  },
};
